### PR TITLE
PR for #11

### PR DESCRIPTION
**Pull request by phax**
As there is no `development` branch I create it in master. This is based on the suggested fix by @fielde at https://github.com/tempusdominus/bootstrap-4/issues/34 - a fix and release would be highly appreciated. The 2 additional lines are identical to the ones starting at line 390. Thanks.

### CODE REVIEW

**Comment by lyhung009** [comment]
Hello @Eonasdan, can you please check this PR?

**Comment by Groman123** [comment]
Any progress here?

**Comment by garbinmarcelo** [comment]
+1 any news?

**Comment by padre** [comment]
Ping @Eonasdan

**Comment by tonix-tuft** [comment]
This project seems to be unmaintained as the maintainer is unresponsive.
I have sent several pull requests, but they all have been ignored.

I have some plans about developing it further, so I have forked both
`tempusdominus/core` and `tempusdominus/bootstrap-4`:

- https://github.com/tonix-tuft/tempusdominus/tree/fork - Tempus Dominus Core (fork of tempusdominus/core)
- https://github.com/tonix-tuft/tempusdominus-bootstrap/tree/fork - Tempus Dominus Bootstrap (fork of tempusdominus/bootstrap-4)

They are also available through NPM:

- http://npmjs.com/tempusdominus
- https://www.npmjs.com/package/tempusdominus-bootstrap

In these two forks (I worked on the `fork` branch on both, not on `master`) I have updated all the NPM dependencies and build scripts,
added some new features and fixed some bugs I have discovered while using Tempus Dominus.

For now, I have left the `master` branch in my forks intact and the same as in the original repos, as I was waiting for my PR being merged
in the original repos and I am adding patches/bugfixes and new features on the `fork` branch in both forked projects.

If you have some pending PR you would like to merge, I invite you to fork my forks instead and we can work
on it together in the free time.

@HaroldPutman already sent me a PR which got merged in tonix-tuft/tempusdominus -> https://github.com/tonix-tuft/tempusdominus/pull/1.

P.S.: I have also created a React version of Tempus Dominus Bootstrap, available here (I hope you enjoy it 😃):

- https://github.com/tonix-tuft/react-tempusdominus-bootstrap - GitHub Repo
- https://tonix-tuft.github.io/react-tempusdominus-bootstrap/ - Demo

**Comment by tonix-tuft** [comment]
Hello guys,

I have sent all the PRs we have already merged into my two forks (https://github.com/tonix-tuft/tempusdominus and https://github.com/tonix-tuft/tempusdominus-bootstrap)
to the main repo of Eonasdan directly on `master`.

I wanna thank @HaroldPutman, @pablo-lp and @zondaTW for their contribution.

I think that now it makes sense for us to continue to work on this project in my two forks and from the `master` branch instead of the `fork` branch I have created and used so far
because I was waiting for @Eonasdan to merge the features we added to its main repo.

But again, as @Eonasdan was and still is unresponsive, I think it would make sense to continue the development from the two forked repos https://github.com/tonix-tuft/tempusdominus and https://github.com/tonix-tuft/tempusdominus-bootstrap now using the `master` branch instead of `fork` as the starting point from which to fork the branches for your PRs.

As always, PRs for new features, bugfixes are welcome! Thank you. Stay tuned.

**Comment by Eonasdan** [comment]
merged

**Comment by phax** [comment]
Nearly 2 years after :D What gives us the honour? ;-)

**Pull request closed without merging**
